/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Separator: typeof import('./src/components/ui/separator/Separator.vue')['default']
    Sheet: typeof import('./src/components/ui/sheet/Sheet.vue')['default']
    SheetClose: typeof import('./src/components/ui/sheet/SheetClose.vue')['default']
    SheetContent: typeof import('./src/components/ui/sheet/SheetContent.vue')['default']
    SheetDescription: typeof import('./src/components/ui/sheet/SheetDescription.vue')['default']
    SheetFooter: typeof import('./src/components/ui/sheet/SheetFooter.vue')['default']
    SheetHeader: typeof import('./src/components/ui/sheet/SheetHeader.vue')['default']
    SheetOverlay: typeof import('./src/components/ui/sheet/SheetOverlay.vue')['default']
    SheetTitle: typeof import('./src/components/ui/sheet/SheetTitle.vue')['default']
    SheetTrigger: typeof import('./src/components/ui/sheet/SheetTrigger.vue')['default']
    Sidebar: typeof import('./src/components/ui/sidebar/Sidebar.vue')['default']
    SidebarContent: typeof import('./src/components/ui/sidebar/SidebarContent.vue')['default']
    SidebarFooter: typeof import('./src/components/ui/sidebar/SidebarFooter.vue')['default']
    SidebarGroup: typeof import('./src/components/ui/sidebar/SidebarGroup.vue')['default']
    SidebarGroupAction: typeof import('./src/components/ui/sidebar/SidebarGroupAction.vue')['default']
    SidebarGroupContent: typeof import('./src/components/ui/sidebar/SidebarGroupContent.vue')['default']
    SidebarGroupLabel: typeof import('./src/components/ui/sidebar/SidebarGroupLabel.vue')['default']
    SidebarHeader: typeof import('./src/components/ui/sidebar/SidebarHeader.vue')['default']
    SidebarInput: typeof import('./src/components/ui/sidebar/SidebarInput.vue')['default']
    SidebarInset: typeof import('./src/components/ui/sidebar/SidebarInset.vue')['default']
    SidebarMenu: typeof import('./src/components/ui/sidebar/SidebarMenu.vue')['default']
    SidebarMenuAction: typeof import('./src/components/ui/sidebar/SidebarMenuAction.vue')['default']
    SidebarMenuBadge: typeof import('./src/components/ui/sidebar/SidebarMenuBadge.vue')['default']
    SidebarMenuButton: typeof import('./src/components/ui/sidebar/SidebarMenuButton.vue')['default']
    SidebarMenuButtonChild: typeof import('./src/components/ui/sidebar/SidebarMenuButtonChild.vue')['default']
    SidebarMenuItem: typeof import('./src/components/ui/sidebar/SidebarMenuItem.vue')['default']
    SidebarMenuSkeleton: typeof import('./src/components/ui/sidebar/SidebarMenuSkeleton.vue')['default']
    SidebarMenuSub: typeof import('./src/components/ui/sidebar/SidebarMenuSub.vue')['default']
    SidebarMenuSubButton: typeof import('./src/components/ui/sidebar/SidebarMenuSubButton.vue')['default']
    SidebarMenuSubItem: typeof import('./src/components/ui/sidebar/SidebarMenuSubItem.vue')['default']
    SidebarProvider: typeof import('./src/components/ui/sidebar/SidebarProvider.vue')['default']
    SidebarRail: typeof import('./src/components/ui/sidebar/SidebarRail.vue')['default']
    SidebarSeparator: typeof import('./src/components/ui/sidebar/SidebarSeparator.vue')['default']
    SidebarTrigger: typeof import('./src/components/ui/sidebar/SidebarTrigger.vue')['default']
    Skeleton: typeof import('./src/components/ui/skeleton/Skeleton.vue')['default']
    Tooltip: typeof import('./src/components/ui/tooltip/Tooltip.vue')['default']
    TooltipContent: typeof import('./src/components/ui/tooltip/TooltipContent.vue')['default']
    TooltipProvider: typeof import('./src/components/ui/tooltip/TooltipProvider.vue')['default']
    TooltipTrigger: typeof import('./src/components/ui/tooltip/TooltipTrigger.vue')['default']
  }
}
